### ISSUE TITLE
This only works if the project file is at the root level of the project

### ISSUE THREAD

**Issue by trondd** [FakeBuild/fake-bootstrap#1]
I tried this after reading the instruction of http://fake.build, but it does not seem to work if I create the project in a sub folder and a solution file at the top level.

**Comment by ushenkodmitry** [comment]
Same here.

> No executable found matching command "dotnet-fake"

**Comment by matthid** [comment]
Yes this is a limitation of the dotnet cli tools. However the next version will have support for global tools. Hopefully we can add that soon (either in dotnet-fake or a new package).

What you can do right now is to add it to more project files.

**Comment by ushenkodmitry** [comment]
Ok, thanks!

ср, 21 февр. 2018 г., 20:20 Matthias Dittrich <notifications@github.com>:

**Comment by matthid** [comment]
This is now mitigated by `dotnet tool install -g fake-cli --version 5.0.0-rc015.176 --source-feed https://www.myget.org/F/fake-vsts/api/v3/index.json` (if you have `2.1.300-rc1-008673`). Will be released soon. (If the version is no longer available you can use latest from https://www.myget.org/feed/fake-vsts/package/nuget/fake-cli)
